<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net10.0-android;net10.0-ios</TargetFrameworks>

		<OutputType>Exe</OutputType>
		<RootNamespace>MediCue</RootNamespace>
		<UseMaui>true</UseMaui>
		<SingleProject>true</SingleProject>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

		<!-- Display name -->
		<ApplicationTitle>MediCue</ApplicationTitle>

		<!-- App Identifier -->
		<ApplicationId>com.companyname.medicue</ApplicationId>

		<!-- Versions -->
		<ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
		<ApplicationVersion>1</ApplicationVersion>

		<!-- To develop, package, and publish an app to the Microsoft Store, see: https://aka.ms/MauiTemplateUnpackaged -->
		<WindowsPackageType>None</WindowsPackageType>

		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">15.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">21.0</SupportedOSPlatformVersion>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net10.0-android|AnyCPU'">
	  <EmbedAssembliesIntoApk>False</EmbedAssembliesIntoApk>
	  <Optimize>False</Optimize>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net10.0-ios|AnyCPU'">
	  <Optimize>False</Optimize>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net10.0-android|AnyCPU'">
	  <Optimize>True</Optimize>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net10.0-ios|AnyCPU'">
	  <Optimize>True</Optimize>
	</PropertyGroup>

	<ItemGroup>
		<!-- App Icon -->
	
		<!-- Splash Screen -->
		
		<!-- Images -->
		<MauiImage Include="Resources\Images\*" />
		<MauiImage Update="Resources\Images\dotnet_bot.png" Resize="True" BaseSize="300,185" />
		
		<!-- Custom Fonts -->
		<MauiFont Include="Resources\Fonts\*" />

		<!-- Raw Assets (also remove the "Resources\Raw" prefix) -->
		<MauiAsset Include="Resources\Raw\**" LogicalName="%(RecursiveDir)%(Filename)%(Extension)" />
	</ItemGroup>

	<ItemGroup>
	  <MauiFont Remove="C:\Users\A155089\.nuget\packages\syncfusion.maui.core\32.1.24\buildTransitive\..\buildTransitive\Resources\Fonts\MauiMaterialAssets.ttf" />
	  <MauiFont Remove="C:\Users\A155089\.nuget\packages\syncfusion.maui.toolkit\1.0.8\buildTransitive\..\buildTransitive\Resources\Fonts\MauiMaterialAssets.ttf" />
	</ItemGroup>

	<ItemGroup>
	  <None Remove="appsettings.Dev.json" />
	  <None Remove="appsettings.json" />
	  <None Remove="appsettings.QA.json" />
	  <None Remove="Resources\AppIcon\appicon.png" />
	  <None Remove="Resources\Splash\splash.png" />
	</ItemGroup>

	<ItemGroup>
	  <EmbeddedResource Include="appsettings.Dev.json" />
	  <EmbeddedResource Include="appsettings.json" />
	  <EmbeddedResource Include="appsettings.QA.json" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="CommunityToolkit.Maui" Version="14.0.0" />
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
		<PackageReference Include="M.BindableProperty.Generator" Version="0.11.1" />
		<PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.2" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.2" />
		<PackageReference Include="Microsoft.Extensions.Http" Version="10.0.2" />
		<PackageReference Include="Microsoft.Maui.Controls" Version="10.0.31" />
		<PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="10.0.2" />
		<PackageReference Include="Plugin.LocalNotification" Version="13.0.0" />
		<PackageReference Include="Riok.Mapperly" Version="4.3.1" />
		<PackageReference Include="Syncfusion.Licensing" Version="32.2.3" />
		<PackageReference Include="Syncfusion.Maui.Chat" Version="32.2.3" />
		<PackageReference Include="Syncfusion.Maui.Core" Version="32.2.3" />
		<PackageReference Include="Syncfusion.Maui.Toolkit" Version="1.0.9" />
		<PackageReference Include="Syncfusion.Pdf.Net.Core" Version="32.2.3" />
		<PackageReference Include="System.Text.Json" Version="10.0.2" />
		<PackageReference Include="ZXing.Net.Maui" Version="0.7.4" />
		<PackageReference Include="ZXing.Net.Maui.Controls" Version="0.7.4" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Enums\" />
	  <Folder Include="Handlers\" />
	</ItemGroup>

	<ItemGroup>
	  <MauiIcon Include="Resources\AppIcon\appicon.png" />
	</ItemGroup>

	<ItemGroup>
	  <MauiSplashScreen Include="Resources\Splash\splash.png" Color="#211359" />
	</ItemGroup>

	<ItemGroup>
	  <Compile Update="Resources\Strings\AppResources.Designer.cs">
	    <DesignTime>True</DesignTime>
	    <AutoGen>True</AutoGen>
	    <DependentUpon>AppResources.resx</DependentUpon>
	  </Compile>
	</ItemGroup>

	<ItemGroup>
	  <EmbeddedResource Update="Resources\Strings\AppResources.resx">
	    <Generator>ResXFileCodeGenerator</Generator>
	    <LastGenOutput>AppResources.Designer.cs</LastGenOutput>
	  </EmbeddedResource>
	</ItemGroup>

	<ItemGroup>
	  <MauiXaml Update="Popups\MedicineMealTablePopup.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Popups\UpdateRoutineCheckupPopup.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\AppSettingsPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
		<MauiXaml Update="Views\HomePage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
	  <MauiXaml Update="Views\AddNewMedicineSchedulePage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\ChatBotPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\EmergencyContactPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\LoginPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\MedicineRoutineSummary.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\MedicineSchedulePage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\MedicineSummaryPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\PersonalDetailsPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\RefillMedicinePage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\ReportsAndSummaryPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\ReportSummaryTextPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\ScanQRToRefillMedicine.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\UpdateMedicineSchedulePage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\UploadReportPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	</ItemGroup>
</Project>
