namespace MediCue.Views;

public partial class ReportSummaryTextPage : ContentPage
{
	public ReportSummaryTextPage(ReportSummaryTextViewModel viewModel)
	{
		InitializeComponent();
		BindingContext = viewModel;
	}

    protected override async void OnAppearing()
    {
        base.OnAppearing();

            await DisplayAlert(
                "Disclaimer",
                "This summary has been generated by AI and may contain inaccuracies or incomplete information. It must not be used as a substitute for professional medical advice, diagnosis, or treatment. Please consult a qualified healthcare professional or the appropriate specialist to verify and interpret the report accurately.",
                "OK");

    }
}